### ISSUE TITLE
error log summary tooling

### ISSUE THREAD

**Issue by MatthiasPuschbeck** [knutschsoft/swapp#14]

**Comment by robertfausk** [comment]
Will try https://bugsnag.com with https://github.com/evolution7/Evolution7BugsnagBundle

**Comment by robertfausk** [comment]
Integration successful.
But we have an issue while deployment: https://github.com/evolution7/Evolution7BugsnagBundle/issues/22
As a workaround we ignore the file 'git_hooks'.

Next step: ask for open source permission.

**Comment by robertfausk** [comment]
Bugsnag will create a new github issue for every server error.
Request for open source permission is sent.
