### ISSUE TITLE
Backend: create user assign Team fails

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#19]
If you create a new User the assigning of the team will not be saved.
Workaround: Edit Teams and assign User there.

**Comment by MatthiasPuschbeck** [comment]
The solution to this problem is documented here:
http://symfony.com/doc/current/cookbook/form/form_collections.html
Searc for:
Doctrine: Cascading Relations and saving the "Inverse" side

**Comment by pueppiblue** [comment]
Final solution to modifiy the inversed side of an association:
[type_option: by_reference](http://symfony.com/doc/current/reference/forms/types/collection.html#by-reference)
