### ISSUE TITLE
Remove test Data

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#20]
There is a lot of testing Data inside the instances. f.i.: Walks and "Orte"

**Comment by robertfausk** [comment]
This is related to #16

**Comment by robertfausk** [comment]
do you mean to delete all test data and keep the test teams and users as they are right now? Is it sufficient to delete this data with phpmyadmin? If we make an new deployment, all testdata will be deleted anyway... and "fresh start data" will be available.

**Comment by robertfausk** [comment]
just keep teams, users and tags?

**Comment by passowst** [comment]
Yes keep it for an easy Start for newbies

**Comment by robertfausk** [comment]
Also added SystemicQuestions to test data cause at least one is needed to create a walk.
