### ISSUE TITLE
Error 500 if "Beobachtung" is empty

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#21]
If you wanna add a Waypoint and the field "Beobachtung" is empty it will be ran in an Error 500

**Comment by pueppiblue** [comment]
Cant reproduce. Client side validation doesnt let me proceed without entering something for "Beobachtung". 
Which browser and version do you use?

**Comment by robertfausk** [comment]
@pueppiblue Try to disable html5 form validation.
E.g. with http://novalidate.com/
