### ISSUE TITLE
Error Message "Disabled" User

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#22]
If User is disabled in the backend (f.i.: Holidays, sickness) an easy Error Message Like: "Nutzer ist derzeit nicht verfügbar" will be better than many lines of "Red Code Terror Screen" ;)

**Comment by robertfausk** [comment]
@passowst Can you provide the path where this message is displayed? Is it if this user tries to log in after he got disabled in backend?

**Comment by passowst** [comment]
![13023469_1245037655514347_1488992681_n](https://cloud.githubusercontent.com/assets/12473785/14582565/45aa79ec-0409-11e6-9277-054be3e3cf3f.jpg)

Yes, when the user is disabled in backend.
And: when new User is created the enabled = checked flag by default will be nice. :+1:
