### ISSUE TITLE
Change Domain to streetworkapp.de

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#23]
Change domain from *.qmsrc.de to .*streetworkapp.de will be so nice :)

swapp1.streetworkapp.de
..
swapp12.streetworkapp.de

Nameserver will be updatet until 18.04.16 to new subdomains

**Comment by robertfausk** [comment]
@passowst @MatthiasPuschbeck What do you think of shorter naming?
e.g.
1.swapp.de
...
12.swapp.de

I think it would be easier to enter and to remember for end users.
Additionally it will save time for them.

**Comment by passowst** [comment]
shorter will be nice and very good for smartphones: but(t) swapp.de, sw-app.de, swapp.org are already registered to another person/business :(
Anyone ideas for shorter URLs?

**Comment by robertfausk** [comment]
from https://www.tonic.to/newname.htm and
https://order.df.eu/germany/bestellung.php?clearsession=1&action=showwhois&globalaction=hosting
https://www.strato.de/buy/ger/domain/display/1

swapp.rocks :D
swapp.pub
swapp.cool
swapp.li
swapp.to
swapp.live
swapp.lol
swapp.systems
swapp.uno

and from https://www.marcaria.com/ws/en/register/domain/domain-registration-multi
swapp.ws
swapp.us (only 9€/year)
swapp.lv

They are all available by now.

**Comment by passowst** [comment]
The users like German "Datenschutz" and funny toplevels don't let trust in swapp.. :( We had to use a serious topleveldomain - *.de ; *.org 
Maybe streetworkapp.de will be the choice :\

**Comment by robertfausk** [comment]
Ok. I'm fine with **streetworkapp.de**

For production instances they will probably use something like swapp.domainname.de (e.g. swapp.gangway.de or swapp.treberhilfe-dresden.de).

**Comment by passowst** [comment]
Nameserver Settings (A Record) for swapp[1..15].streetworkapp.de added right now.

**Comment by robertfausk** [comment]
I think now we only need to change vhost-config files on the server. Actually they are mapped to the old domain names.

**Comment by passowst** [comment]
Nice!

**Comment by robertfausk** [comment]
Feel free to test.
