### ISSUE TITLE
Increase upload_max_filesize from 2048 KiB to a higher value

### ISSUE THREAD

**Issue by robertfausk** [knutschsoft/swapp#46]
## Error in swapp

**Symfony\Component\HttpFoundation\File\Exception\FileException** in **POST /app.php/waypointcreated/58**
The file "DSC_5243.JPG" exceeds your upload_max_filesize ini directive (limit is 2048 KiB).

[View on Bugsnag](https://app.bugsnag.com/knutschsoft/swapp/errors/58a1acce805be87fe9c25de5?event_id=58a1acce5372c61100617878)

## Stacktrace

    vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/UploadedFile.php:235 - Symfony\Component\HttpFoundation\File\UploadedFile::move
    vendor/vich/uploader-bundle/Storage/FileSystemStorage.php:22 - Vich\UploaderBundle\Storage\FileSystemStorage::doUpload
    vendor/vich/uploader-bundle/Storage/AbstractStorage.php:67 - Vich\UploaderBundle\Storage\AbstractStorage::upload
    vendor/vich/uploader-bundle/Handler/UploadHandler.php:64 - Vich\UploaderBundle\Handler\UploadHandler::upload
    var/cache/prod/appProdProjectContainer.php:4972 - VichUploaderBundleHandlerUploadHandler_000000002b758dcc000000004201f572e3fdfd3b365808eb65f12eccd4fa1078::upload
    vendor/vich/uploader-bundle/EventListener/Doctrine/UploadListener.php:41 - Vich\UploaderBundle\EventListener\Doctrine\UploadListener::prePersist
    vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:63 - Symfony\Bridge\Doctrine\ContainerAwareEventManager::dispatchEvent
    vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117 - Doctrine\ORM\Event\ListenersInvoker::invoke
    vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:896 - Doctrine\ORM\UnitOfWork::persistNew
    vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1683 - Doctrine\ORM\UnitOfWork::doPersist
    vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1639 - Doctrine\ORM\UnitOfWork::persist
    vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:579 - Doctrine\ORM\EntityManager::persist
    src/AppBundle/Repository/DoctrineORMWayPointRepository.php:48 - AppBundle\Repository\DoctrineORMWayPointRepository::save
    src/AppBundle/Controller/WayPointController.php:125 - AppBundle\Controller\WayPointController::createWayPointAction
    var/bootstrap.php.cache:2510 - Symfony\Component\HttpKernel\HttpKernel::handleRaw
    var/bootstrap.php.cache:2472 - Symfony\Component\HttpKernel\HttpKernel::handle
    vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169 - Symfony\Component\HttpKernel\Kernel::handle
    web/app.php:27 - [main]

[View full stacktrace](https://app.bugsnag.com/knutschsoft/swapp/errors/58a1acce805be87fe9c25de5?event_id=58a1acce5372c61100617878)

**Comment by robertfausk** [comment]
I would suggest 10MB.

**Comment by pueppiblue** [comment]
php.ini setting.
I'm sure an op will help us.

In addition we could (should) validate the filesize on form submission.
@Vich\UploadableField also offers an option `filesize`. Not sure if it works as validation constraint though.

**Comment by robertfausk** [comment]
> In addition we could (should) validate the filesize on form submission.
@vich\UploadableField also offers an option filesize. Not sure if it works as validation constraint though.

Can you provide a PR for this please?

**Comment by robertfausk** [comment]
It's not fixed cause user still have can't upload images larger than 2048 KiB.
With PR #64 user won't get a server error but a nice error message instead.

@pueppiblue Can you provide another PR for a 10MB image size assertion and for php.ini setting in docker file & readme? This new PR can be merged when server side php ini settings are adjusted.

**Comment by robertfausk** [comment]
Already solved on 1 Dec 2017. :octopus:
