### ISSUE TITLE
Fixing "215 Char Issue" / Linebreaks in Waypoint Review.

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#47]
Fixing "215 Char Issue" / Linebreaks in Waypoint Review. 

The first User commited Bug after a long time 👍 
"Hallo in die Gruppe. Wenn ich auf dem mobilen Chrome-Browser (Tablett und Smartphone) oder im Browser (Firefox und Chrome) eine Runde oder einen Wegpunkt nachlesen möchte, kann ich das bei den Textfeldern nicht vollständig tun. Die Textfelder scheinen auf max. 215 Zeichen begrenzt zu sein. Das betrifft zb. das Feld Beobachtung (bei Wegpunkten) oder Reflexion (bei Runden). Könntet Ihr das beheben? Ansonsten scheint die App recht funktionstüchtig zu sein, wenn man sie einmal eingerichtet hat. Wenn Ihr das Problem beheben könnt, würde ich anfangen die App mal im Langzeittest zu nutzen."

**Comment by robertfausk** [comment]
Increased field length of walkReflection of walk, question of systemicQuestion and note of waypoint from 255 to 4096.
All instances of App released.
