### ISSUE TITLE
all users are admin users

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#51]
Since last emergency Update all users are with admin privileges.

**Comment by robertfausk** [comment]
Sorry, can't reproduce. E.g. on swapp1 user eva_beta hasn't role admin and therefore can't reach backend.

Can you give more information:
Which instance?
Which user?
What is this user allowed to do what he shouldn't be allowed to do?

**Comment by robertfausk** [comment]
@passowst Feel free to reopen if this issue still exists.
