### ISSUE TITLE
swapp02 needs new Admin user

### ISSUE THREAD

**Issue by passowst** [knutschsoft/swapp#52]
the admin user was deleted by users. Needs a new Admin with default password in swapp02

**Comment by robertfausk** [comment]
Solve hint:
Use command line with fos user bundle command on server (bin/console fos:user:create or something like that)

Donnerstag, 4. Mai 2017, 19:54 +0200 von passowst  <notifications@github.com>:

**Comment by robertfausk** [comment]
@passowst Done.
