### ISSUE TITLE
Upgrade to Symfony 3.3

### ISSUE THREAD

**Issue by pueppiblue** [knutschsoft/swapp#54]
With Symfony 3.3 having been released end of june, we should upgrade the app correspondingly. 
I am hereby volunteering for the chore.

**Comment by robertfausk** [comment]
Yep. Feel free to start a PR.

**Comment by robertfausk** [comment]
After Symfony 3.3 we can start to use Webpack Encore instead of plain webpack.
On top of this we can much simplier embed a theme like bootstrap or material design.

**Comment by robertfausk** [comment]
Maybe the changes from regression branch have to be merge first.
https://github.com/knutschsoft/swapp/tree/regression
Can you check it up?
