### ISSUE TITLE
Upgrade FOSUserBundle to least stable version

### ISSUE THREAD

**Issue by robertfausk** [knutschsoft/swapp#57]
We are still relying on a dev version but stable version is already out. It's 2.0.1 atm.

For upgrade see https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md and https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Changelog.md

**Comment by pueppiblue** [comment]
The config node "from_email" in FOSUserBundle configuration is now required and cannot be null.
Thus the parameter 'mailer_user' has to be set in parameters.yml.
A pointer to this should maybe added in README.md.

PhpStorm also gave me an advice to install another bundle:
> 
Warning:(20, 5) Please add roave/security-advisories:dev-master as a firewall for vulnerable components.

This could fix the failing security check in VersionEye regarding bootstrap as long as we haven't migrated to MD yet. Should be an issue of its own though.

**Comment by robertfausk** [comment]
Could you open an issue for roave/security-advisories? 

Btw: It’s enough to link the PR in this issue once. No need for every commit.

**Comment by pueppiblue** [comment]
> Btw: It’s enough to link the PR in this issue once. No need for every commit.

Not sure what my course of action should be now?!
My current practice is to append the ticket number to every commit, which apparently led to the pollution of this issue. I'm not sure it always worked like that or why this happened (maybe putting a 57 into the branch name is faulty)
e.g. no pollution to be seen on #36
So should i omit any reference in the commit message or reference the pr instead. But without any commit there is no pr.  :confused:

**Comment by robertfausk** [comment]
> So should i omit any reference in the commit message or reference the pr instead. But without any commit there is no pr.  :confused:

Your commit belongs automatically to your PR and so your commit message belongs to the PR and everything is fine. You can also take a look in big projects like symfony/symfony e.g.
If you want to explicitly reference an issue from a commit then you can of course link this issue in commit message.

FOSUserBundle is upgraded. Thanks! So I will close this issue.
