### ISSUE TITLE
add roave/security-advisories:dev-master to the stack

### ISSUE THREAD

**Issue by pueppiblue** [knutschsoft/swapp#59]
As pointed out in #57 adding roave/security-advisories could alleviate some of our security liabilities.

**Comment by pueppiblue** [comment]
> This package does not provide any API or usable classes: its only purpose is to prevent installation of software with known and documented security issues. [...] and you will not be able to harm yourself with software with known security vulnerabilities.
> The checks are only executed when adding a new dependency via composer require or when running composer update: deploying an application with a valid composer.lock and via composer install won't trigger any security versions checking.

It won't fix any already existing security issue just prevent future ones. So no chance of fixing bootstrap or swiftmailer security issues.

**Comment by robertfausk** [comment]
We could add a test in travis where we do a 'composer update' and check its result.

**Comment by robertfausk** [comment]
Closed in favor of #91.
