### ISSUE TITLE
age groups should be configurable via frontend

### ISSUE THREAD

**Issue by pueppiblue** [knutschsoft/swapp#72]
Age groups used by Treberhilfe Dresden are different from our predefined age groups.
These age groups constitute a changing requirement depending on the association which uses the app.
Thus the age groups need to be configurable.

We should also make sure to preserve exiting age group data while migrating to a new database schema.

**Comment by robertfausk** [comment]
* user can configure teams
![image](https://user-images.githubusercontent.com/1651297/52619479-04b41080-2ea2-11e9-847c-64d3d79fa269.png)
* configure age groups per team
![image](https://user-images.githubusercontent.com/1651297/52619499-14cbf000-2ea2-11e9-975a-0b50cbabc4a7.png)
* set age group data per waypoint
![image](https://user-images.githubusercontent.com/1651297/52620966-5ced1180-2ea6-11e9-9aba-50689f55da35.png)
